/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TCONNDDEF_H
#define TCONNDDEF_H


#ifndef TDR_METALIB_TCONND_VERSION 
#define TDR_METALIB_TCONND_VERSION 	11 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TCONND_HASH 
#define TDR_METALIB_TCONND_HASH 	"d7341cc1f25274c63b06fc03d5995297" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define TCONND_NAME_LEN                          	32
#define TCONND_SVRSKEY_LEN                       	128
#define TCONND_URL_LEN                           	128
#define TCONND_MAX_TDR                           	16
#define TCONND_MAX_PDU                           	16
#define TCONND_MAX_NETTRANS                      	16
#define TCONND_SVRSKEY_MAX_INST                  	16
#define TCONND_DEF_SENDCHECK_INTERVAL            	10
#define TCONND_DEF_RECVCHECK_INTERVAL            	10
#define TCONND_DEFAULT_UP_PKG_LEN                	4096
#define TCONND_DEFAULT_DOWN_PKG_LEN              	65536
#define TCONND_MAX_VIPNUM                        	64

/* PDULenParserID*/
enum tagPDULenParserID 
{
    PDULENPARSERID_BY_TDR = 0, 	/* 使用TDR方法进行分析 */
    PDULENPARSERID_BY_NULL = 1, 	/* 通过数据中出现NULL('\0')字符分析长度 */
    PDULENPARSERID_BY_QQ = 2, 	/* use qq default method */
    PDULENPARSERID_BY_NONE = 10, 	/* Do nothing ,just forward */
};

/* ID_MSG_TCONND*/
enum tagID_MSG_TCONND 
{
    ID_MSG_TCONND_REPORT = 48, 
    ID_MSG_TCONND_ASKREPORT = 49, 
    ID_MSG_TCONND_UPDATE = 50, 
};


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagTransLimit;
typedef struct tagTransLimit                       	TRANSLIMIT;
typedef struct tagTransLimit                       	*LPTRANSLIMIT;

struct tagTransMetric;
typedef struct tagTransMetric                      	TRANSMETRIC;
typedef struct tagTransMetric                      	*LPTRANSMETRIC;

struct tagConnLimit;
typedef struct tagConnLimit                        	CONNLIMIT;
typedef struct tagConnLimit                        	*LPCONNLIMIT;

struct tagConnStatInfo;
typedef struct tagConnStatInfo                     	CONNSTATINFO;
typedef struct tagConnStatInfo                     	*LPCONNSTATINFO;

struct tagConnMetric;
typedef struct tagConnMetric                       	CONNMETRIC;
typedef struct tagConnMetric                       	*LPCONNMETRIC;

struct tagTDR;
typedef struct tagTDR                              	TDR;
typedef struct tagTDR                              	*LPTDR;

struct tagTDRList;
typedef struct tagTDRList                          	TDRLIST;
typedef struct tagTDRList                          	*LPTDRLIST;

struct tagPDULenTDRParser;
typedef struct tagPDULenTDRParser                  	PDULENTDRPARSER;
typedef struct tagPDULenTDRParser                  	*LPPDULENTDRPARSER;

struct tagPDULenQQParser;
typedef struct tagPDULenQQParser                   	PDULENQQPARSER;
typedef struct tagPDULenQQParser                   	*LPPDULENQQPARSER;

union tagPDULenParser;
typedef union  tagPDULenParser                     	PDULENPARSER;
typedef union  tagPDULenParser                     	*LPPDULENPARSER;

struct tagPDU;
typedef struct tagPDU                              	PDU;
typedef struct tagPDU                              	*LPPDU;

struct tagPDUList;
typedef struct tagPDUList                          	PDULIST;
typedef struct tagPDUList                          	*LPPDULIST;

struct tagListener;
typedef struct tagListener                         	LISTENER;
typedef struct tagListener                         	*LPLISTENER;

struct tagListenerList;
typedef struct tagListenerList                     	LISTENERLIST;
typedef struct tagListenerList                     	*LPLISTENERLIST;

struct tagListenerRun;
typedef struct tagListenerRun                      	LISTENERRUN;
typedef struct tagListenerRun                      	*LPLISTENERRUN;

struct tagListenerRunList;
typedef struct tagListenerRunList                  	LISTENERRUNLIST;
typedef struct tagListenerRunList                  	*LPLISTENERRUNLIST;

struct tagSerializer;
typedef struct tagSerializer                       	SERIALIZER;
typedef struct tagSerializer                       	*LPSERIALIZER;

struct tagSerializerList;
typedef struct tagSerializerList                   	SERIALIZERLIST;
typedef struct tagSerializerList                   	*LPSERIALIZERLIST;

struct tagSerializerRun;
typedef struct tagSerializerRun                    	SERIALIZERRUN;
typedef struct tagSerializerRun                    	*LPSERIALIZERRUN;

struct tagSerializerRunList;
typedef struct tagSerializerRunList                	SERIALIZERRUNLIST;
typedef struct tagSerializerRunList                	*LPSERIALIZERRUNLIST;

struct tagNetTrans;
typedef struct tagNetTrans                         	NETTRANS;
typedef struct tagNetTrans                         	*LPNETTRANS;

struct tagNetTransList;
typedef struct tagNetTransList                     	NETTRANSLIST;
typedef struct tagNetTransList                     	*LPNETTRANSLIST;

struct tagNetTransRun;
typedef struct tagNetTransRun                      	NETTRANSRUN;
typedef struct tagNetTransRun                      	*LPNETTRANSRUN;

struct tagNetTransRunList;
typedef struct tagNetTransRunList                  	NETTRANSRUNLIST;
typedef struct tagNetTransRunList                  	*LPNETTRANSRUNLIST;

struct tagtconnd;
typedef struct tagtconnd                           	TCONND;
typedef struct tagtconnd                           	*LPTCONND;

struct tagtconndrun_status;
typedef struct tagtconndrun_status                 	TCONNDRUN_STATUS;
typedef struct tagtconndrun_status                 	*LPTCONNDRUN_STATUS;

struct tagtconndrun_cumulate;
typedef struct tagtconndrun_cumulate               	TCONNDRUN_CUMULATE;
typedef struct tagtconndrun_cumulate               	*LPTCONNDRUN_CUMULATE;

struct tagSvrsKeyHead;
typedef struct tagSvrsKeyHead                      	SVRSKEYHEAD;
typedef struct tagSvrsKeyHead                      	*LPSVRSKEYHEAD;

struct tagSvrsKeyData;
typedef struct tagSvrsKeyData                      	SVRSKEYDATA;
typedef struct tagSvrsKeyData                      	*LPSVRSKEYDATA;

struct tagSvrsKeyList;
typedef struct tagSvrsKeyList                      	SVRSKEYLIST;
typedef struct tagSvrsKeyList                      	*LPSVRSKEYLIST;

struct tagSvrsKeyInst;
typedef struct tagSvrsKeyInst                      	SVRSKEYINST;
typedef struct tagSvrsKeyInst                      	*LPSVRSKEYINST;

struct tagSvrsKeyInstList;
typedef struct tagSvrsKeyInstList                  	SVRSKEYINSTLIST;
typedef struct tagSvrsKeyInstList                  	*LPSVRSKEYINSTLIST;

struct tagTconndSvrsKeyVerReport;
typedef struct tagTconndSvrsKeyVerReport           	TCONNDSVRSKEYVERREPORT;
typedef struct tagTconndSvrsKeyVerReport           	*LPTCONNDSVRSKEYVERREPORT;

struct tagTconndSvrsKeyUpdate;
typedef struct tagTconndSvrsKeyUpdate              	TCONNDSVRSKEYUPDATE;
typedef struct tagTconndSvrsKeyUpdate              	*LPTCONNDSVRSKEYUPDATE;

struct tagTconndinnerMsgHead;
typedef struct tagTconndinnerMsgHead               	TCONNDINNERMSGHEAD;
typedef struct tagTconndinnerMsgHead               	*LPTCONNDINNERMSGHEAD;

union tagTconndinnerMsgBody;
typedef union  tagTconndinnerMsgBody               	TCONNDINNERMSGBODY;
typedef union  tagTconndinnerMsgBody               	*LPTCONNDINNERMSGBODY;

struct tagTconndinnerMsg;
typedef struct tagTconndinnerMsg                   	TCONNDINNERMSG;
typedef struct tagTconndinnerMsg                   	*LPTCONNDINNERMSG;

struct tagBusidList;
typedef struct tagBusidList                        	BUSIDLIST;
typedef struct tagBusidList                        	*LPBUSIDLIST;

struct tagtconndkeymgr;
typedef struct tagtconndkeymgr                     	TCONNDKEYMGR;
typedef struct tagtconndkeymgr                     	*LPTCONNDKEYMGR;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagTransLimit
{
    int iPkgSpeed;                      
    int iByteSpeed;                     
};

struct tagTransMetric
{
    tdr_longlong llSendPkgSucc;                  
    tdr_longlong llSendByteSucc;                 
    tdr_longlong llSendPkgFail;                  
    tdr_longlong llSendByteFail;                 
    tdr_longlong llSendPkgDrop;                  
    tdr_longlong llSendByteDrop;                 
    tdr_longlong llRecvPkgSucc;                  
    tdr_longlong llRecvByteSucc;                 
    tdr_longlong llRecvPkgFail;                  
    tdr_longlong llRecvByteFail;                 
    tdr_longlong llRecvPkgDrop;                  
    tdr_longlong llRecvByteDrop;                 
};

struct tagConnLimit
{
    int iMaxConn;                       
    int iPermit;                        
    int iSpeed;                         
};

struct tagConnStatInfo
{
    int iTotal;                         
    int iIdle;                          
    int iWait;                          
    int iActive;                        
};

struct tagConnMetric
{
    int iTry;                           
    int iRefuse;                        
    int iNetLost;                       
    int iAllocFail;                     
    int iEpollFail;                     
    int iAcceptFail;                    
    int iNetFail;                       
};

struct tagTDR
{
    char szName[TCONND_NAME_LEN];        
    char szPath[TCONND_URL_LEN];         
};

struct tagTDRList
{
    int iCount;                         
    TDR astTDRs[TCONND_MAX_TDR];        
};

/* 使用TDR方法来分析数据包的长度 */
struct tagPDULenTDRParser
{
    char szTDR[TCONND_NAME_LEN];          	/*   PDU数据结构所在元数据描述库文件 */
    char szPkg[TCONND_NAME_LEN];          	/*   PDU数据结构元数据描述名 */
    char szPkgLen[TCONND_NAME_LEN];       	/*   PDU数据结构中记录数据包总长度信息成员的元数据描述路径名 */
    char szHeadLen[TCONND_NAME_LEN];      	/*   PDU数据结构中记录数据包头部长度信息的成员的元数据描述路径名 */
    char szBodyLen[TCONND_NAME_LEN];      	/*   PDU数据结构中记录数据包消息体长度信息的成员的元数据描述路径名 */
    int iPkgLenMultiplex;               
    int iHeadLenMultiplex;              
    int iBodyLenMultiplex;              
};

/* 使用TDR方法来分析数据包的长度, use default tdr */
struct tagPDULenQQParser
{
    char szTDR[TCONND_NAME_LEN];          	/*   PDU数据结构所在元数据描述库文件 */
    char szSendPkg[TCONND_NAME_LEN];      	/*   PDU数据结构上行数据包描述名 */
    char szRecvPkg[TCONND_NAME_LEN];      	/*   PDU数据结构下行数据包描述名 */
    int iSigValidSec;                   
    int iCheckCltIP;                    
    int iEncMethod;                      	/*    Bind Macrosgroup:TSEC_ENC,*/
    int iAuthType;                       	/*    Bind Macrosgroup:TSEC_AUTH,*/
    int iCheckSig2;                     
    int iSvrSKeyLen;                    
    char szSvrSKey[TCONND_SVRSKEY_LEN];  
    int iSvrSKey2Len;                   
    char szSvrSKey2[TCONND_SVRSKEY_LEN]; 
    int iTestNumEnable;                 
    int iTestSvrSKeyLen;                
    char szTestSvrSKey[TCONND_SVRSKEY_LEN];
    int iTestSvrSKey2Len;               
    char szTestSvrSKey2[TCONND_SVRSKEY_LEN];
    int iTestBeginNum;                  
    int iTestEndNum;                    
    short nVIPNum;                        
    int vIPUins[TCONND_MAX_VIPNUM];     
    int iSvrsKeyAutoUpdate;             
};

/* 分析协议数据单元(PDU)长度信息的数据结构，用于将数据流分解成应用定义的数据通信消息 */
union tagPDULenParser
{
    PDULENTDRPARSER stTDRParser;                     	/* PDULENPARSERID_BY_TDR,  使用TDR方法进行分析 */
    PDULENQQPARSER stQQParser;                      	/* PDULENPARSERID_BY_QQ,  use default qq parser */
};

struct tagPDU
{
    char szName[TCONND_NAME_LEN];        
    int iUpSize;                         	/*   PDU数据单元上行包最大字节数 */
    int iDownSize;                       	/*   PDU数据单元下行包最大字节数 */
    int iLenParsertype;                  	/*  Ver.11  Bind Macrosgroup:PDULenParserID,*/
    PDULENPARSER stLenParser;                     	/*  Ver.11 分析协议数据单元(PDU)长度信息的成员 */
};

struct tagPDUList
{
    int iCount;                         
    PDU astPDUs[TCONND_MAX_PDU];        
};

struct tagListener
{
    char szName[TCONND_NAME_LEN];        
    char szUrl[TCONND_URL_LEN];          
    int iSendBuff;                      
    int iRecvBuff;                      
    int iMaxIdle;                       
    int iBacklog;                       
};

struct tagListenerList
{
    int iCount;                         
    LISTENER astListeners[TCONND_MAX_NETTRANS];
};

struct tagListenerRun
{
    char szName[TCONND_NAME_LEN];        
    TRANSMETRIC stTransStat;                    
    CONNMETRIC stConnStat;                     
};

struct tagListenerRunList
{
    int iCount;                         
    LISTENERRUN astListeners[TCONND_MAX_NETTRANS];
};

struct tagSerializer
{
    char szName[TCONND_NAME_LEN];        
    char szUrl[TCONND_URL_LEN];          
};

struct tagSerializerList
{
    int iCount;                         
    SERIALIZER astSerializers[TCONND_MAX_NETTRANS];
};

struct tagSerializerRun
{
    char szName[TCONND_NAME_LEN];        
    TRANSMETRIC stTransStat;                    
};

struct tagSerializerRunList
{
    int iCount;                         
    SERIALIZERRUN astSerializers[TCONND_MAX_NETTRANS];
};

struct tagNetTrans
{
    char szName[TCONND_NAME_LEN];        
    int iUseTimeStamp;                  
    int iUseWaitQueue;                  
    int iQueueNotifyInterval;           
    char szPDU[TCONND_NAME_LEN];         
    char szListener[TCONND_NAME_LEN];    
    char szSerializer[TCONND_NAME_LEN];  
    char szLisViewer[TCONND_NAME_LEN];   
    char szSerViewer[TCONND_NAME_LEN];   
    CONNLIMIT stConnLimit;                    
    TRANSLIMIT stTransLimit;                   
};

struct tagNetTransList
{
    int iCount;                         
    NETTRANS astNetTrans[TCONND_MAX_NETTRANS];
};

struct tagNetTransRun
{
    char szName[TCONND_NAME_LEN];        
    CONNSTATINFO stConnInfo;                     
    CONNMETRIC stConnStat;                     
    TRANSMETRIC stTransStat;                    
};

struct tagNetTransRunList
{
    int iCount;                         
    NETTRANSRUN astNetTrans[TCONND_MAX_NETTRANS];
};

struct tagtconnd
{
    int iThreading;                     
    int iEnableViewer;                  
    int iMaxFD;                         
    TDRLIST stTDRList;                      
    PDULIST stPDUList;                      
    LISTENERLIST stListenerList;                 
    SERIALIZERLIST stSerializerList;               
    NETTRANSLIST stNetTransList;                 
};

struct tagtconndrun_status
{
    int iUpTime;                        
    int iNow;                           
};

struct tagtconndrun_cumulate
{
    LISTENERRUNLIST stListenerRunList;              
    SERIALIZERRUNLIST stSerializerRunList;            
    NETTRANSRUNLIST stNetTransRunList;              
};

struct tagSvrsKeyHead
{
    int iBusid;                         
    int iPDU;                           
    char szResv[56];                     
};

struct tagSvrsKeyData
{
    char szPDUName[TCONND_NAME_LEN];     
    int iSvrSKeyLen;                    
    char szSvrSKey[TCONND_SVRSKEY_LEN];  
    int iSvrSKey2Len;                   
    char szSvrSKey2[TCONND_SVRSKEY_LEN]; 
};

struct tagSvrsKeyList
{
    int iCount;                         
    SVRSKEYDATA astSvrsKey[TCONND_MAX_PDU];     
};

struct tagSvrsKeyInst
{
    SVRSKEYHEAD stHead;                         
    SVRSKEYLIST stBody;                         
};

struct tagSvrsKeyInstList
{
    int iCount;                         
    SVRSKEYINST astSvrsKeyInstList[TCONND_SVRSKEY_MAX_INST];
};

struct tagTconndSvrsKeyVerReport
{
    SVRSKEYLIST stSvrsKeyList;                  
};

struct tagTconndSvrsKeyUpdate
{
    SVRSKEYLIST stSvrsKeyList;                  
};

struct tagTconndinnerMsgHead
{
    unsigned short wVersion;                        	/*   通信协议版本 */
    unsigned short wPkgLen;                         	/*   消息总体的长度 */
    unsigned short wCmdID;                          	/*   命令号 */
    unsigned short wMagic;                          	/*   通信协议魔数 */
};

union tagTconndinnerMsgBody
{
    TCONNDSVRSKEYVERREPORT stTconndSvrsKeyVerReport;        	/* ID_MSG_TCONND_REPORT,   */
    TCONNDSVRSKEYUPDATE stTconndSvrsKeyUpdate;           	/* ID_MSG_TCONND_UPDATE,   */
};

/*  */
struct tagTconndinnerMsg
{
    TCONNDINNERMSGHEAD stHead;                         
    TCONNDINNERMSGBODY stBody;                         
};

struct tagBusidList
{
    int iCount;                         
    int busid[256];                     
};

struct tagtconndkeymgr
{
    int iLogLevel;                       	/*   日志等级 */
    tdr_ip_t ulCenterdAddr;                   	/*   centerd地址 */
    tdr_ip_t ulTconndMgrAddr;                 	/*   tconndkeymgr地址 */
    char szBindAddr[64];                  	/*   绑定IP地址 */
    unsigned short wBindPort;                       	/*   绑定端口地址 */
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TCONNDDEF_H */
