/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TAPP_BASEDATA_DEF_H
#define TAPP_BASEDATA_DEF_H


#ifndef TDR_METALIB_TAPP_BASEDATA_DEF_VERSION 
#define TDR_METALIB_TAPP_BASEDATA_DEF_VERSION 	1 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TAPP_BASEDATA_DEF_HASH 
#define TDR_METALIB_TAPP_BASEDATA_DEF_HASH 	"2b4fae75cfcae0e1c76a82aa1b576854" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */



#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagtapp_basedata;
typedef struct tagtapp_basedata                    	TAPP_BASEDATA;
typedef struct tagtapp_basedata                    	*LPTAPP_BASEDATA;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagtapp_basedata
{
    float fProcMaxTime;                    	/*   tapp no-idle proc max process time in basedata timer, unit ms */
    float fProcMinTime;                    	/*   tapp no-idle proc min process time in basedata timer, unit ms */
    float fProcTotalTime;                  	/*   tapp no-idle proc total process time in basedata timer, unit ms */
    long lProcTotalNum;                   	/*   tapp no-idle proc total num in basedata timer */
    long lIdleTotalNum;                   	/*   tapp idle total num in basedata timer */
    float fTickMaxTime;                    	/*   tapp tick max process time in basedata timer, unit ms */
    float fTickMinTime;                    	/*   tapp tick proc min process time in basedata timer, unit ms */
    float fTickTotalTime;                  	/*   tapp tick proc total process time in basedata timer, unit ms */
    long lTickTotalNum;                   	/*   tapp tick proc total num in basedata timer */
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TAPP_BASEDATA_DEF_H */
