/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TCLIENT_DEF_H
#define TCLIENT_DEF_H


#ifndef TDR_METALIB_CLIENT_DEF_VERSION 
#define TDR_METALIB_CLIENT_DEF_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_CLIENT_DEF_HASH 
#define TDR_METALIB_CLIENT_DEF_HASH 	"c4d8d5a67334c826ffadbcd42a65bf6b" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define SEVER_URL_MAX_LEN                        	64
#define SEVER_KEY_LEN                            	32


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagclient_def;
typedef struct tagclient_def                       	CLIENT_DEF;
typedef struct tagclient_def                       	*LPCLIENT_DEF;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagclient_def
{
    char szGameSvrUrl[SEVER_URL_MAX_LEN];
    int iUin;                           
    char szSvrKey[SEVER_KEY_LEN];        
    int iAuthType;                      
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TCLIENT_DEF_H */
