/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TAPP_RUNDATA_TIMER_DEF_H
#define TAPP_RUNDATA_TIMER_DEF_H


#ifndef TDR_METALIB_TAPP_RUNDATA_TIMER_DEF_VERSION 
#define TDR_METALIB_TAPP_RUNDATA_TIMER_DEF_VERSION 	1 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TAPP_RUNDATA_TIMER_DEF_HASH 
#define TDR_METALIB_TAPP_RUNDATA_TIMER_DEF_HASH 	"098192c36de9627f527d8b6e18493bc0" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */



#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagtapp_basedata_timer;
typedef struct tagtapp_basedata_timer              	TAPP_BASEDATA_TIMER;
typedef struct tagtapp_basedata_timer              	*LPTAPP_BASEDATA_TIMER;

struct tagtapp_rundata_status_timer;
typedef struct tagtapp_rundata_status_timer        	TAPP_RUNDATA_STATUS_TIMER;
typedef struct tagtapp_rundata_status_timer        	*LPTAPP_RUNDATA_STATUS_TIMER;

struct tagtapp_rundata_cumu_timer;
typedef struct tagtapp_rundata_cumu_timer          	TAPP_RUNDATA_CUMU_TIMER;
typedef struct tagtapp_rundata_cumu_timer          	*LPTAPP_RUNDATA_CUMU_TIMER;

struct tagtapp_rundata_timer;
typedef struct tagtapp_rundata_timer               	TAPP_RUNDATA_TIMER;
typedef struct tagtapp_rundata_timer               	*LPTAPP_RUNDATA_TIMER;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagtapp_basedata_timer
{
    long lGlobalTime;                     	/*   global base data timer */
};

struct tagtapp_rundata_status_timer
{
    long lGlobalTime;                     	/*   global run data status val timer */
};

struct tagtapp_rundata_cumu_timer
{
    long lGlobalTime;                     	/*   global run data cumulate val timer */
};

struct tagtapp_rundata_timer
{
    TAPP_BASEDATA_TIMER stBasedata_timer;                	/*   base data timer */
    TAPP_RUNDATA_STATUS_TIMER stRundata_status_timer;          	/*   run data status val timer */
    TAPP_RUNDATA_CUMU_TIMER stRundata_cumu_timer;            	/*   run data cumulate val timer */
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TAPP_RUNDATA_TIMER_DEF_H */
