/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TSEC_IPACL_DESC_H
#define TSEC_IPACL_DESC_H


#ifndef TDR_METALIB_TSEC_IP_VERSION 
#define TDR_METALIB_TSEC_IP_VERSION 	1 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TSEC_IP_HASH 
#define TDR_METALIB_TSEC_IP_HASH 	"b15986e3749d2f29fb0d2f867ae36c10" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */



#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagIPLimit;
typedef struct tagIPLimit                          	IPLIMIT;
typedef struct tagIPLimit                          	*LPIPLIMIT;

struct tagIPACL;
typedef struct tagIPACL                            	IPACL;
typedef struct tagIPACL                            	*LPIPACL;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagIPLimit
{
    char szLimit[8];                     
    char szSrcIP[128];                   
    char szDstIP[128];                   
};

struct tagIPACL
{
    char szDefaultRule[8];               
    int iLimitCnt;                      
    IPLIMIT astLimits[1024];                
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TSEC_IPACL_DESC_H */
