/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TSEC_CONF_DESC_H
#define TSEC_CONF_DESC_H


#ifndef TDR_METALIB_TSEC_VERSION 
#define TDR_METALIB_TSEC_VERSION 	1 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TSEC_HASH 
#define TDR_METALIB_TSEC_HASH 	"ec987da12d48a1f0a0b218878658309a" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */



#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagTsecConf;
typedef struct tagTsecConf                         	TSECCONF;
typedef struct tagTsecConf                         	*LPTSECCONF;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagTsecConf
{
    char szFuncFile[256];                
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TSEC_CONF_DESC_H */
