/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TFRAMEHEAD_H
#define TFRAMEHEAD_H


#ifndef TDR_METALIB_TFRAMEHEAD_VERSION 
#define TDR_METALIB_TFRAMEHEAD_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TFRAMEHEAD_HASH 
#define TDR_METALIB_TFRAMEHEAD_HASH 	"97df3c947d017fd1bc5ac29284aa58d3" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define TFRAMEHEAD_CMD_START                     	0 	/* 连接初始包 */
#define TFRAMEHEAD_CMD_STOP                      	1 	/* 连接断开包 */
#define TFRAMEHEAD_CMD_INPROC                    	2 	/* 通信包 */
#define TFRAMEHEAD_CMD_RELAY                     	3 	/* 重连包 */
#define TFRAMEHEAD_CMD_NOTIFY                    	4 	/* 预占连接包 */
#define TFRAMEHEAD_CMD_SETROUTING                	5 	/* 路由跳转包 */
#define TFRAMEHEAD_CMD_RSP_SETROUTING            	6 	/* 路由跳转回应包 */
#define TFRAMEHEAD_CMD_SETCONNLIMIT              	7 	/* 服务器连接限制设置包 */
#define TFRAMEHEAD_CMD_RSP_SETCONNLIMIT          	8 	/* 服务器连接限制设置返回包 */
#define TFRAMEHEAD_MAX_BATCH_IDENT               	512
#define TFRAMEHEAD_EXTRA_IP                      	1
#define TFRAMEHEAD_TIMESTAMP_TIMEVAL             	1
#define SERLIZER_NAME_LEN                        	32
#define NETTRANS_NAME_LEN                        	32
#define TFRAMEHEAD_SET_ROUTING                   	1

/* TFRAMEHEAD_STOP_REASON*/
enum tagTFRAMEHEAD_STOP_REASON 
{
    TFRAMEHEAD_REASON_NONE = 0, 
    TFRAMEHEAD_REASON_IDLE_CLOSE = 1, 	/* 连接空闲关闭 */
    TFRAMEHEAD_REASON_PEER_CLOSE = 2, 	/* 客户端关闭 */
    TFRAMEHEAD_REASON_NETWORK_FAIL = 3, 	/* 网络异常关闭 */
    TFRAMEHEAD_REASON_BAD_PKGLEN = 4, 	/* 请求包长度异常关闭 */
    TFRAMEHEAD_REASON_TCONND_SHUTDOWN = 6, 	/* tconnd重启 */
    TFRAMEHEAD_REASON_SELF_CLOSE = 7, 	/* 服务器主动下发关闭 */
    TFRAMEHEAD_REASON_AUTH_FAIL = 8, 	/* 客户端连接验证失败 */
    TFRAMEHEAD_REASON_TRANS_LOST = 9, 	/* 连接已释放 */
    TFRAMEHEAD_REASON_ENC_NOSUP = 10, 	/* 未用 */
    TFRAMEHEAD_REASON_SVR_CLOSE = 11, 	/* 预留给服务器 */
    TFRAMEHEAD_REASON_SVR_KICKOFF = 12, 	/* 预留给服务器 */
    TFRAMEHEAD_REASON_CLI_RELOGIN = 13, 	/* 预留给服务器 */
    TFRAMEHEAD_REASON_CLI_LOGOUT = 14, 	/* 预留给服务器 */
    TFRAMEHEAD_REASON_EXCEED_LIMIT = 20, 	/* 客户端发送速度太快 */
    TFRAMEHEAD_REASON_SVR_RESV = 100, 
};

/* TFRAMEHEAD_SETROUTING_RESULT*/
enum tagTFRAMEHEAD_SETROUTING_RESULT 
{
    SETROUTING_RESULT_SUCCESS = 0, 
    SETROUTING_RESULT_FAIL_EXCEED_LIMIT = 1, 
    SETROUTING_RESULT_FAIL_SERLIZER_UNKNOWN = 2, 
};

/* TFRAMEHEAD_SETCONNLIMIT_RESULT*/
enum tagTFRAMEHEAD_SETCONNLIMIT_RESULT 
{
    SETCONNLIMIT_RESULT_SUCCESS = 0, 
    SETCONNLIMIT_RESULT_FAIL_INVALID_DATA = 1, 
    SETCONNLIMIT_RESULT_FAIL_NETTRANS_UNKNOWN = 2, 
};

/* TFRAMEHEAD_RELAYTYPE*/
enum tagTFRAMEHEAD_RELAYTYPE 
{
    TFRAMEHEAD_JUMP_SERVER_RELAY = 1, 
    TFRAMEHEAD_NETWORK_FAILURE_RELAY = 2, 
    TFRAMEHEAD_CLIENT_CRASH_RELAY = 3, 
};
#define TFRAMEHEAD_CONNECTKEY_LEN                	16
#define TFRAMEHEAD_IDENTITY_LEN                  	16


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagTIPInfo;
typedef struct tagTIPInfo                          	TIPINFO;
typedef struct tagTIPInfo                          	*LPTIPINFO;

union tagTFrameHeadData;
typedef union  tagTFrameHeadData                   	TFRAMEHEADDATA;
typedef union  tagTFrameHeadData                   	*LPTFRAMEHEADDATA;

struct tagTFrameAuthQQ;
typedef struct tagTFrameAuthQQ                     	TFRAMEAUTHQQ;
typedef struct tagTFrameAuthQQ                     	*LPTFRAMEAUTHQQ;

union tagTFrameAuthData;
typedef union  tagTFrameAuthData                   	TFRAMEAUTHDATA;
typedef union  tagTFrameAuthData                   	*LPTFRAMEAUTHDATA;

struct tagTFrameCmdStart;
typedef struct tagTFrameCmdStart                   	TFRAMECMDSTART;
typedef struct tagTFrameCmdStart                   	*LPTFRAMECMDSTART;

struct tagTFrameCmdStop;
typedef struct tagTFrameCmdStop                    	TFRAMECMDSTOP;
typedef struct tagTFrameCmdStop                    	*LPTFRAMECMDSTOP;

struct tagTFrameIdent;
typedef struct tagTFrameIdent                      	TFRAMEIDENT;
typedef struct tagTFrameIdent                      	*LPTFRAMEIDENT;

struct tagTFrameCmdInProc;
typedef struct tagTFrameCmdInProc                  	TFRAMECMDINPROC;
typedef struct tagTFrameCmdInProc                  	*LPTFRAMECMDINPROC;

struct tagTFrameCmdRelay;
typedef struct tagTFrameCmdRelay                   	TFRAMECMDRELAY;
typedef struct tagTFrameCmdRelay                   	*LPTFRAMECMDRELAY;

struct tagTFrameCmdSetRouting;
typedef struct tagTFrameCmdSetRouting              	TFRAMECMDSETROUTING;
typedef struct tagTFrameCmdSetRouting              	*LPTFRAMECMDSETROUTING;

struct tagTFrameCmdSetRoutingRsp;
typedef struct tagTFrameCmdSetRoutingRsp           	TFRAMECMDSETROUTINGRSP;
typedef struct tagTFrameCmdSetRoutingRsp           	*LPTFRAMECMDSETROUTINGRSP;

union tagTRoutingOption;
typedef union  tagTRoutingOption                   	TROUTINGOPTION;
typedef union  tagTRoutingOption                   	*LPTROUTINGOPTION;

struct tagTFrameCmdNotify;
typedef struct tagTFrameCmdNotify                  	TFRAMECMDNOTIFY;
typedef struct tagTFrameCmdNotify                  	*LPTFRAMECMDNOTIFY;

struct tagTFrameCmdSetConnLimit;
typedef struct tagTFrameCmdSetConnLimit            	TFRAMECMDSETCONNLIMIT;
typedef struct tagTFrameCmdSetConnLimit            	*LPTFRAMECMDSETCONNLIMIT;

struct tagTFrameCmdSetConnLimitRsp;
typedef struct tagTFrameCmdSetConnLimitRsp         	TFRAMECMDSETCONNLIMITRSP;
typedef struct tagTFrameCmdSetConnLimitRsp         	*LPTFRAMECMDSETCONNLIMITRSP;

union tagTFrameCmdData;
typedef union  tagTFrameCmdData                    	TFRAMECMDDATA;
typedef union  tagTFrameCmdData                    	*LPTFRAMECMDDATA;

struct tagTTimeVal;
typedef struct tagTTimeVal                         	TTIMEVAL;
typedef struct tagTTimeVal                         	*LPTTIMEVAL;

union tagTTimeStampData;
typedef union  tagTTimeStampData                   	TTIMESTAMPDATA;
typedef union  tagTTimeStampData                   	*LPTTIMESTAMPDATA;

struct tagtframehead;
typedef struct tagtframehead                       	TFRAMEHEAD;
typedef struct tagtframehead                       	*LPTFRAMEHEAD;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagTIPInfo
{
    short nFamily;                        
    unsigned short wPort;                          
    tdr_ip_t ulIp;                           
};

union tagTFrameHeadData
{
    TIPINFO stIPInfo;                        	/* TFRAMEHEAD_EXTRA_IP,   */
};

struct tagTFrameAuthQQ
{
    long lUin;                           
};

union tagTFrameAuthData
{
    TFRAMEAUTHQQ stAuthQQV1;                      	/* TSEC_AUTH_QQV1,   */
    TFRAMEAUTHQQ stAuthQQV2;                      	/* TSEC_AUTH_QQV2,   */
    TFRAMEAUTHQQ stAuthQQUnified;                 	/* TSEC_AUTH_QQUNIFIED,   */
};

/* 连接建立包 */
struct tagTFrameCmdStart
{
    int iAuthType;                       	/*    Bind Macrosgroup:TSEC_AUTH,*/
    TFRAMEAUTHDATA stAuthData;                     
    int iWaitTime;                       	/*   连接排队时间 */
};

/* 连接断开包 */
struct tagTFrameCmdStop
{
    int iReason;                        
};

/* 连接标识 */
struct tagTFrameIdent
{
    int iID;                            
    int iConnIdx;                       
};

struct tagTFrameCmdInProc
{
    char chValid;                         	/*   是否组播,0:单播 1:组播 */
    char chNoEnc;                         	/*   下行包是否加密 */
    short nCount;                          	/*   组播个数 */
    TFRAMEIDENT astIdents[TFRAMEHEAD_MAX_BATCH_IDENT];
};

struct tagTFrameCmdRelay
{
    long lUin;                           
    int iRelayType;                     
    TFRAMEIDENT stOld;                          
    TFRAMEIDENT stNew;                          
};

struct tagTFrameCmdSetRouting
{
    char szSerializerName[SERLIZER_NAME_LEN]; 	/*   bus标识名 */
    int iID;                             	/*   新的连接在逻辑服务端上的索引,含义同head字段 */
};

/* 跳转路由回应包 */
struct tagTFrameCmdSetRoutingRsp
{
    int iResult;                         	/*    Bind Macrosgroup:TFRAMEHEAD_SETROUTING_RESULT,*/
};

/* 跳转路由请求包 */
union tagTRoutingOption
{
    TFRAMECMDSETROUTING stCmdRouting;                    	/* TFRAMEHEAD_SET_ROUTING,   */
};

/* 占位请求包 */
struct tagTFrameCmdNotify
{
    long lUin;                           
    char szConnKey[TFRAMEHEAD_CONNECTKEY_LEN];
    char szIdentity[TFRAMEHEAD_IDENTITY_LEN];
    unsigned char bISetRouting;                    	/*   是否设置路由 */
    TROUTINGOPTION stRouting;                       	/*   路由选项 */
};

/* 设置连接限制 */
struct tagTFrameCmdSetConnLimit
{
    char szNetTransName[NETTRANS_NAME_LEN];
    int iPermit;                         	/*   服务器能处理最大连接数 */
    int iSpeed;                          	/*   每一百毫秒放行连接数 */
};

/* 设置连接限制回应包 */
struct tagTFrameCmdSetConnLimitRsp
{
    int iResult;                         	/*    Bind Macrosgroup:TFRAMEHEAD_SETCONNLIMIT_RESULT,*/
};

union tagTFrameCmdData
{
    TFRAMECMDSTART stStart;                         	/* TFRAMEHEAD_CMD_START,   */
    TFRAMECMDSTOP stStop;                          	/* TFRAMEHEAD_CMD_STOP,   */
    TFRAMECMDINPROC stInProc;                        	/* TFRAMEHEAD_CMD_INPROC,   */
    TFRAMECMDRELAY stRelay;                         	/* TFRAMEHEAD_CMD_RELAY,   */
    TFRAMECMDNOTIFY stNotify;                        	/* TFRAMEHEAD_CMD_NOTIFY,   */
    TFRAMECMDSETROUTING stSetRouting;                    	/* TFRAMEHEAD_CMD_SETROUTING,   */
    TFRAMECMDSETROUTINGRSP stSetRoutingRsp;                 	/* TFRAMEHEAD_CMD_RSP_SETROUTING,   */
    TFRAMECMDSETCONNLIMIT stSetConnLimit;                  	/* TFRAMEHEAD_CMD_SETCONNLIMIT,   */
    TFRAMECMDSETCONNLIMITRSP stSetConnLimitRsp;               	/* TFRAMEHEAD_CMD_RSP_SETCONNLIMIT,   */
};

struct tagTTimeVal
{
    int iSec;                           
    int iUsec;                          
};

union tagTTimeStampData
{
    TTIMEVAL stTimeVal;                       	/* TFRAMEHEAD_TIMESTAMP_TIMEVAL,   */
};

struct tagtframehead
{
    char chVer;                           	/*   版本信息,默认为零 */
    char chCmd;                           	/*   包头类型 */
    char chExtraType;                     	/*   是否带连接URL信息,由ID字段决定 */
    char chTimeStampType;                 	/*   是否带时间戳,由tconnd配置 */
    int iID;                             	/*   由逻辑服务器回写,连接索引,若不回写,则通过URL表示连接 */
    int iConnIdx;                        	/*   服务器只读,tconnd连接索引 */
    TFRAMEHEADDATA stExtraInfo;                     	/*   连接 URL信息 */
    TTIMESTAMPDATA stTimeStamp;                     	/*   时间戳信息 */
    TFRAMECMDDATA stCmdData;                       	/*   扩展信息 */
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TFRAMEHEAD_H */
