/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TPDUDEF_H
#define TPDUDEF_H

/*   
 User Define Macros.   */

#define TPDU_MAX_ENCRYPTSKEY_LEN                 	128
#define TPDU_MAX_ENCRYPTIDENT_LEN                	64
#define TPDU_MAX_ENCRYPTSYN_LEN                  	128
#define TPDU_MAX_ENCRYPTSYNACK_LEN               	128
#define TPDU_MAGIC                               	85
#define TPDU_VERSION                             	11 	/* 协议版本 */

/* TPDU_CMD*/
enum tagTPDU_CMD 
{
    TPDU_CMD_NONE = 0, 	/* 通信包 */
    TPDU_CMD_CHGSKEY = 1, 	/* 交换密钥(下行) */
    TPDU_CMD_QUEINFO = 2, 	/* 排队信息(下行) */
    TPDU_CMD_AUTH = 3, 	/* 签名请求信息(上行) */
    TPDU_CMD_IDENT = 4, 	/* 连接建立(下行) */
    TPDU_CMD_PLAIN = 5, 	/* 未加密通信包(下行) */
    TPDU_CMD_RELAY = 6, 	/* 重连请求信息(上行) */
    TPDU_CMD_STOP = 7, 	/* 未用 */
    TPDU_CMD_SYN = 8, 	/* 连接握手信息(下行) */
    TPDU_CMD_SYNACK = 9, 	/* 三次握手请求(上行) */
};

/* TPDU_RELAY_TYPE*/
enum tagTPDU_RELAY_TYPE 
{
    TPDU_JUMP_SERVER_RELAY = 1, 	/* 跨服跳转 */
    TPDU_NETWORK_FAILURE_RELAY = 2, 	/* 断线重连 */
    TPDU_CLIENT_CRASH_RELAY = 3, 	/* 保留值 */
};

/* TPDU_STOP_REASON*/
enum tagTPDU_STOP_REASON 
{
    TPDU_STOP_TCONND_SHUTDOWN = 6, 
    TPDU_STOP_SVR_CLOSE = 11, 
    TPDU_STOP_SVR_KICKOFF = 12, 
    TPDU_STOP_CLI_RELOGIN = 13, 
    TPDU_STOP_CLI_LOGOUT = 14, 
};


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagTPDUBase;
typedef struct tagTPDUBase                         	TPDUBASE;
typedef struct tagTPDUBase                         	*LPTPDUBASE;

struct tagTPDUExtChgSkey;
typedef struct tagTPDUExtChgSkey                   	TPDUEXTCHGSKEY;
typedef struct tagTPDUExtChgSkey                   	*LPTPDUEXTCHGSKEY;

struct tagTPDUExtQueInfo;
typedef struct tagTPDUExtQueInfo                   	TPDUEXTQUEINFO;
typedef struct tagTPDUExtQueInfo                   	*LPTPDUEXTQUEINFO;

union tagTPDUExtAuthData;
typedef union  tagTPDUExtAuthData                  	TPDUEXTAUTHDATA;
typedef union  tagTPDUExtAuthData                  	*LPTPDUEXTAUTHDATA;

struct tagTPDUExtAuthInfo;
typedef struct tagTPDUExtAuthInfo                  	TPDUEXTAUTHINFO;
typedef struct tagTPDUExtAuthInfo                  	*LPTPDUEXTAUTHINFO;

struct tagTPDUIdentInfo;
typedef struct tagTPDUIdentInfo                    	TPDUIDENTINFO;
typedef struct tagTPDUIdentInfo                    	*LPTPDUIDENTINFO;

struct tagTPDUExtIdent;
typedef struct tagTPDUExtIdent                     	TPDUEXTIDENT;
typedef struct tagTPDUExtIdent                     	*LPTPDUEXTIDENT;

struct tagTPDUExtRelay;
typedef struct tagTPDUExtRelay                     	TPDUEXTRELAY;
typedef struct tagTPDUExtRelay                     	*LPTPDUEXTRELAY;

struct tagTPDUExtStop;
typedef struct tagTPDUExtStop                      	TPDUEXTSTOP;
typedef struct tagTPDUExtStop                      	*LPTPDUEXTSTOP;

struct tagTPDUSynInfo;
typedef struct tagTPDUSynInfo                      	TPDUSYNINFO;
typedef struct tagTPDUSynInfo                      	*LPTPDUSYNINFO;

struct tagTPDUExtSyn;
typedef struct tagTPDUExtSyn                       	TPDUEXTSYN;
typedef struct tagTPDUExtSyn                       	*LPTPDUEXTSYN;

struct tagTPDUExtSynAck;
typedef struct tagTPDUExtSynAck                    	TPDUEXTSYNACK;
typedef struct tagTPDUExtSynAck                    	*LPTPDUEXTSYNACK;

union tagTPDUExt;
typedef union  tagTPDUExt                          	TPDUEXT;
typedef union  tagTPDUExt                          	*LPTPDUEXT;

struct tagTPDUHead;
typedef struct tagTPDUHead                         	TPDUHEAD;
typedef struct tagTPDUHead                         	*LPTPDUHEAD;

struct tagTPDUEncHead;
typedef struct tagTPDUEncHead                      	TPDUENCHEAD;
typedef struct tagTPDUEncHead                      	*LPTPDUENCHEAD;

struct tagTPDUFrame;
typedef struct tagTPDUFrame                        	TPDUFRAME;
typedef struct tagTPDUFrame                        	*LPTPDUFRAME;



/*   Define structs/unions.   */

#pragma pack(1)

/* 基础包头信息 */
struct tagTPDUBase
{
    unsigned char bMagic;                          	/*   魔数 */
    unsigned char bVersion;                        	/*   协议版本,参考TPDU_VERSION */
    unsigned char bCmd;                            	/*   包类型 */
    unsigned char bHeadLen;                        	/*   包头长度 */
    unsigned char bEncHeadLen;                     	/*  Ver.11 上行包有效,包头附加信息长度,与body一起加密 */
    int iBodyLen;                        	/*   包体长度 */
};

/* 交换密钥 */
struct tagTPDUExtChgSkey
{
    short nType;                           	/*   默认填零 */
    short nLen;                            	/*   密钥长度(密文) */
    char szEncryptSkey[TPDU_MAX_ENCRYPTSKEY_LEN];
};

/* 排队信息 */
struct tagTPDUExtQueInfo
{
    int iPos;                            	/*   在队列中位置 */
    int iMax;                            	/*   队列的长度 */
};

/* 签名数据 */
union tagTPDUExtAuthData
{
    TQQAUTHINFO stAuthQQV1;                      	/* TSEC_AUTH_QQV1,  0x82协议 */
    TQQAUTHINFO stAuthQQV2;                      	/* TSEC_AUTH_QQV2,  0x82协议 */
    TQQUNIFIEDAUTHINFO stAuthQQUnified;                 	/* TSEC_AUTH_QQUNIFIED,  0XDE协议 */
};

/* 签名请求包 */
struct tagTPDUExtAuthInfo
{
    int iEncMethod;                      	/*  Ver.11 通信加解密类型 Bind Macrosgroup:TSEC_ENC,*/
    int iAuthType;                       	/*   签名类型 Bind Macrosgroup:TSEC_AUTH,*/
    TPDUEXTAUTHDATA stAuthData;                      	/*   签名数据 */
};

/* 连接建立包 */
struct tagTPDUIdentInfo
{
    int iPos;                            	/*   连接索引和验证字符串可以保存为以后的重连 */
    char szIdent[TQQ_IDENT_LEN];          	/*   连接验证字符串 */
};

struct tagTPDUExtIdent
{
    int iLen;                            	/*   连接建立包信息长度(密文) */
    char szEncryptIdent[TPDU_MAX_ENCRYPTIDENT_LEN];
};

/* 重连请求包 */
struct tagTPDUExtRelay
{
    int iEncMethod;                      	/*  Ver.11 通信加解密类型 Bind Macrosgroup:TSEC_ENC,*/
    int iRelayType;                      	/*   重连类型 */
    int iOldPos;                         	/*   占位连接索引 */
    int iLen;                            	/*   重连验证信息长度(密文) */
    char szEncryptIdent[TPDU_MAX_ENCRYPTIDENT_LEN];
};

/* 保留,暂未用 */
struct tagTPDUExtStop
{
    int iStopReason;                    
};

/* 连接握手信息 */
struct tagTPDUSynInfo
{
    char szRandstr[TQQ_IDENT_LEN];       
};

struct tagTPDUExtSyn
{
    unsigned char bLen;                            	/*   连接握手信息长度(密文) */
    char szEncryptSynInfo[TPDU_MAX_ENCRYPTSYN_LEN];
};

/* 三次握手请求信息 */
struct tagTPDUExtSynAck
{
    unsigned char bLen;                            	/*   握手请求信息长度(密文),结构同连接握手信息结构 */
    unsigned char szEncryptSynInfo[TPDU_MAX_ENCRYPTSYNACK_LEN];
};

/* 包头扩展信息 */
union tagTPDUExt
{
    TPDUEXTCHGSKEY stChgSkey;                       	/* TPDU_CMD_CHGSKEY,   */
    TPDUEXTQUEINFO stQueInfo;                       	/* TPDU_CMD_QUEINFO,   */
    TPDUEXTAUTHINFO stAuthInfo;                      	/* TPDU_CMD_AUTH,   */
    TPDUEXTIDENT stIdent;                         	/* TPDU_CMD_IDENT,   */
    TPDUEXTRELAY stRelay;                         	/* TPDU_CMD_RELAY,   */
    TPDUEXTSTOP stStop;                          	/* TPDU_CMD_STOP,   */
    TPDUEXTSYN stSyn;                           	/* TPDU_CMD_SYN,   */
    TPDUEXTSYNACK stSynAck;                        	/* TPDU_CMD_SYNACK,   */
};

/* 包头 */
struct tagTPDUHead
{
    TPDUBASE stBase;                          	/*   基础信息 */
    TPDUEXT stExt;                           	/*   扩展信息 */
};

/* 附加头部信息,不要定义字符串或者网络序和本地序不等的数据类型 */
struct tagTPDUEncHead
{
    unsigned int dwSequence;                     
};

/* CS通信包= 明文:包头(基础信息+扩展信息)+密文:包体(附加头部信息+应用包 */
struct tagTPDUFrame
{
    TPDUHEAD stHead;                         
    char szBody[1];                      
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* TPDUDEF_H */
