/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef PROTOCOL_H
#define PROTOCOL_H


#ifndef TDR_METALIB_CSPKG_VERSION 
#define TDR_METALIB_CSPKG_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_CSPKG_HASH 
#define TDR_METALIB_CSPKG_HASH 	"dccf11ea60ee2d30bffb1bfb971ceda9" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define PACKAGE_DATA_LEN                         	1024
#define CMD_LOGIN                                	1
#define CMD_LOGOUT                               	2
#define CMD_HELLO                                	3


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagsamplehead;
typedef struct tagsamplehead                       	SAMPLEHEAD;
typedef struct tagsamplehead                       	*LPSAMPLEHEAD;

struct tagsamplelogin;
typedef struct tagsamplelogin                      	SAMPLELOGIN;
typedef struct tagsamplelogin                      	*LPSAMPLELOGIN;

struct tagsamplelogout;
typedef struct tagsamplelogout                     	SAMPLELOGOUT;
typedef struct tagsamplelogout                     	*LPSAMPLELOGOUT;

struct tagsamplehello;
typedef struct tagsamplehello                      	SAMPLEHELLO;
typedef struct tagsamplehello                      	*LPSAMPLEHELLO;

union tagsamplebody;
typedef union  tagsamplebody                       	SAMPLEBODY;
typedef union  tagsamplebody                       	*LPSAMPLEBODY;

struct tagCSPKG;
typedef struct tagCSPKG                            	CSPKG;
typedef struct tagCSPKG                            	*LPCSPKG;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagsamplehead
{
    unsigned short wVersion;                       
    unsigned short wCmd;                           
    unsigned short wHeadlen;                       
    unsigned short wBodylen;                       
};

struct tagsamplelogin
{
    int iUin;                           
};

struct tagsamplelogout
{
    int iUin;                           
};

struct tagsamplehello
{
    int iUin;                           
    char szData[PACKAGE_DATA_LEN];       
};

union tagsamplebody
{
    SAMPLELOGIN stLogin;                         	/* CMD_LOGIN,   */
    SAMPLELOGOUT stLogout;                        	/* CMD_LOGOUT,   */
    SAMPLEHELLO stHello;                         	/* CMD_HELLO,   */
};

struct tagCSPKG
{
    SAMPLEHEAD stHead;                         
    SAMPLEBODY stBody;                         
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* PROTOCOL_H */
