/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

/*       Version Number: 1          */

#ifndef RESCONV_H
#define RESCONV_H

/*   Define Macros.   */

#define RES_FILE_MAGIC                           	1397052237
#define RES_TRANSLATE_VERSION                    	1


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagResHead;
typedef struct tagResHead                          	RESHEAD;
typedef struct tagResHead                          	*LPRESHEAD;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagResHead
{
    int iMagic;                         
    int iVersion;                       
    int iUnit;                          
    int iCount;                         
};

#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* RESCONV_H */
